StarterBot connected and running!
Traceback (most recent call last):
  File "bot/autobot.py", line 377, in <module>
    main()
  File "bot/autobot.py", line 369, in main
    command, channel, user = parse_slack_output(slack_client.rtm_read())
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/slackclient/_client.py", line 126, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/slackclient/_server.py", line 155, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/home/macro/autobotz/autobot_installs/local/lib/python2.7/site-packages/websocket/_socket.py", line 80, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
